import { StyleSheet } from "react-native";
import { BORDER_RADIUS, COLORS, FONT_SIZE, FONT_WEIGHT, SHADOWS, SPACING } from "../constants/constants";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  content: {
    padding: SPACING.lg,
    paddingTop: SPACING.xxxl,
  },
  title: {
    fontSize: FONT_SIZE.xxxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: FONT_SIZE.lg,
    color: COLORS.TEXT_SECONDARY,
    marginBottom: SPACING.xl,
    textAlign: 'center',
    lineHeight: 24,
  },
  errorContainer: {
    backgroundColor: COLORS.ERROR_LIGHT,
    padding: SPACING.md,
    borderRadius: BORDER_RADIUS.lg,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.ERROR + "40",
  },
  errorText: {
    color: COLORS.ERROR,
    fontSize: FONT_SIZE.sm,
    textAlign: "center",
    fontWeight: FONT_WEIGHT.medium,
  },
  successContainer: {
    backgroundColor: COLORS.SUCCESS_LIGHT,
    padding: SPACING.md,
    borderRadius: BORDER_RADIUS.lg,
    marginBottom: SPACING.xl,
    borderWidth: 1,
    borderColor: COLORS.SUCCESS + "40",
  },
  successText: {
    color: COLORS.SUCCESS,
    fontSize: FONT_SIZE.sm,
    textAlign: "center",
    lineHeight: 20,
    fontWeight: FONT_WEIGHT.medium,
  },
  input: {
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    fontSize: FONT_SIZE.md,
    color: COLORS.TEXT_PRIMARY,
    backgroundColor: COLORS.WHITE,
    fontWeight: FONT_WEIGHT.medium,
    minHeight: 56,
  },
  inputFocused: {
    borderColor: COLORS.PRIMARY,
    ...SHADOWS.colored,
  },
  button: {
    backgroundColor: COLORS.PRIMARY,
    paddingVertical: SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    alignItems: "center",
    marginTop: SPACING.md,
    marginBottom: SPACING.lg,
    minHeight: 56,
    justifyContent: 'center',
    ...SHADOWS.medium,
  },
  buttonDisabled: {
    backgroundColor: COLORS.GRAY_300,
    ...SHADOWS.small,
  },
  buttonText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.semibold,
  },
  linkText: {
    color: COLORS.PRIMARY,
    fontSize: FONT_SIZE.md,
    textAlign: "center",
    marginTop: SPACING.md,
    fontWeight: FONT_WEIGHT.semibold,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.sm,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    borderRadius: BORDER_RADIUS.sm,
    marginRight: SPACING.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.WHITE,
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: COLORS.PRIMARY,
    borderColor: COLORS.PRIMARY,
  },
  checkmark: {
    color: COLORS.WHITE,
    fontSize: 14,
    fontWeight: FONT_WEIGHT.bold,
  },
  checkboxText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.TEXT_PRIMARY,
    flex: 1,
    lineHeight: 22,
    fontWeight: FONT_WEIGHT.medium,
  },
});